---
dist: bionic
os: linux
language: python
services:
  - docker

before_install:
  - sudo apt-get -qq update

env:
  global:
    - ROLE_NAME: chrony
  jobs:
    - MOLECULE_IMAGE=centos-7 MOLECULE_COMMAND=/usr/sbin/init
    - MOLECULE_IMAGE=centos-8 MOLECULE_COMMAND=/usr/sbin/init
    - MOLECULE_IMAGE=fedora-32 MOLECULE_COMMAND=/usr/sbin/init
    - MOLECULE_IMAGE=fedora-31 MOLECULE_COMMAND=/usr/lib/systemd/systemd
    - MOLECULE_IMAGE=fedora-30 MOLECULE_COMMAND=/usr/lib/systemd/systemd
    - MOLECULE_IMAGE=ubuntu-16.04 MOLECULE_COMMAND=/sbin/init
    - MOLECULE_IMAGE=ubuntu-18.04 MOLECULE_COMMAND=/lib/systemd/systemd
    - MOLECULE_IMAGE=ubuntu-20.04 MOLECULE_COMMAND=/lib/systemd/systemd
    - MOLECULE_IMAGE=debian-9 MOLECULE_COMMAND=/lib/systemd/systemd
    - MOLECULE_IMAGE=debian-10 MOLECULE_COMMAND=/lib/systemd/systemd

jobs:
  fast_finish: true
install:
  - pip install -r requirements.txt

before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME ericsysmin.$ROLE_NAME
  - cd ericsysmin.$ROLE_NAME

script:
  - molecule --debug test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
